<a href="https://colab.research.google.com/github/NeoASJ/ML-Supervised-learning-/blob/main/linearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Building a Linear Regression Model to Predict Fuel Efficiency (MPG) Using the Auto MPG  Dataset**

In [ ]:
import zipfile
import os

# Unzip the file
with zipfile.ZipFile("/content/auto+mpg.zip", 'r') as zip:
    zip.extractall("/content/auto_mpg_zip")

import pandas as pd

column_names = [
    "mpg", "cylinders", "displacement", "horsepower", "weight",
    "acceleration", "model_year", "origin", "car_name"
]
# get data from desired file and create a dataframe
df = pd.read_csv("//content/auto_mpg_zip/auto-mpg.data",
                 delim_whitespace=True,
                 names=column_names,
                 na_values="?")

In [65]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

**Data Preprocessing**

In [66]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [67]:
#To fill missing horsepower values with the median horsepower of cars having the same number of cylinders
df['horsepower'] = df.groupby('cylinders')['horsepower'].transform(lambda x : x.fillna(x.median()))
df['horsepower'].isnull().sum()
# independent and dependent variables are identified
x = df.drop(["car_name","mpg"],axis = 1)
y = df["mpg"]

In [ ]:
# import of different modules
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 41)
model = LinearRegression()
# fitting of model
model.fit(x_train,y_train)

In [57]:
# outcome of model's prediction
y_pred = model.predict(x_test)

In [58]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# y_test: true mpg values
# y_pred: predicted mpg values from your model

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
# Calculate RMSE by taking the square root of MSE
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f} mpg")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f} mpg")
print(f"R² score: {r2:.2f}")

MAE: 3.25 mpg
MSE: 18.99
RMSE: 4.36 mpg
R² score: 0.78

In [59]:
accuarcy = model.score(x_test,y_test)
print('The accuarcy of model is  ',round(accuarcy,2)*100)

The accuarcy of model is   78.0